controller_list:
  - name: fake_ur3_controller
    joints:
      - ur3_shoulder_pan_joint
      - ur3_shoulder_lift_joint
      - ur3_elbow_joint
      - ur3_wrist_1_joint
      - ur3_wrist_2_joint
      - ur3_wrist_3_joint
  - name: fake_robotiq_2f_140_controller
    joints:
      - robotiq_2f_140_left_outer_knuckle_joint
initial:
  - group: ur3
    pose: ready #robot_gripper_test, ready
