controller_list:
  - name: /pos_traj_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
  #- name: /joint_group_vel_controller #/vel_based_pos_traj_controller or /pos_based_pos_traj_controller or /joint_group_vel_controller
  #  type: velocity_controllers/JointGroupVelocityController
    default: true
    joints:
      - ur3_shoulder_pan_joint
      - ur3_shoulder_lift_joint
      - ur3_elbow_joint
      - ur3_wrist_1_joint
      - ur3_wrist_2_joint
      - ur3_wrist_3_joint
  - name: ""
    action_ns: robotiq_2f_140
    type: GripperCommand
    default: true
    joints:
      - robotiq_2f_140_left_outer_knuckle_joint
